/**
 * 공통 컴포넌트(atomic).
 *  atoms      더 쪼갤 수 없는 조각(단추 · 배지 · 입력 · 시각 …)
 *  molecules  조각 몇 개를 묶은 것(양식 칸 · 페이지 머리 · 수치 타일 · 권한 흐림 …)
 *  organisms  화면 한 부분을 맡는 것(상태 화면 · 상단바 · 사이드바 · 모바일 서랍 · 메뉴 조각)
 *  templates  화면 틀(AppLayout: 사이드바 + 상단바 + 본문, 모바일은 서랍)
 * 모든 컴포넌트는 className 을 받아 cn 으로 합친다. 뒤에 준 클래스가 이긴다.
 */

// atoms
export { Badge } from './atoms/Badge'
export type { BadgeProps } from './atoms/Badge'
export { Button } from './atoms/Button'
export type { ButtonProps } from './atoms/Button'
export { buttonClasses } from './atoms/button-styles'
export type { ButtonClassOptions, ButtonSize, ButtonVariant } from './atoms/button-styles'
export { Card, CardHeader } from './atoms/Card'
export type { CardHeaderProps, CardProps } from './atoms/Card'
export { Chip } from './atoms/Chip'
export type { ChipProps } from './atoms/Chip'
export { Divider } from './atoms/Divider'
export type { DividerProps } from './atoms/Divider'
export { fieldClasses } from './atoms/field-styles'
export type { FieldSize } from './atoms/field-styles'
export * from './atoms/icons'
export { Input } from './atoms/Input'
export type { InputProps } from './atoms/Input'
export { Kbd } from './atoms/Kbd'
export { Label } from './atoms/Label'
export type { LabelProps } from './atoms/Label'
export { Select } from './atoms/Select'
export type { SelectProps } from './atoms/Select'
export { SeverityBadge } from './atoms/SeverityBadge'
export type { SeverityBadgeProps } from './atoms/SeverityBadge'
export { Skeleton } from './atoms/Skeleton'
export { Spinner } from './atoms/Spinner'
export type { SpinnerProps } from './atoms/Spinner'
export { StatusDot } from './atoms/StatusDot'
export type { Signal, StatusDotProps } from './atoms/StatusDot'
export { Switch } from './atoms/Switch'
export type { SwitchProps } from './atoms/Switch'
export { Textarea } from './atoms/Textarea'
export type { TextareaProps } from './atoms/Textarea'
export { Time } from './atoms/Time'
export type { TimeProps } from './atoms/Time'
export { SEVERITY_CLASS, SOFT_TONE, TEXT_TONE, VERDICT_CLASS } from './atoms/tones'
export type { Tone } from './atoms/tones'
export { VerdictBadge } from './atoms/VerdictBadge'
export type { VerdictBadgeProps } from './atoms/VerdictBadge'

// molecules
export { Banner } from './molecules/Banner'
export type { BannerProps, BannerTone } from './molecules/Banner'
export { FormField } from './molecules/FormField'
export type { FieldControlProps, FormFieldProps } from './molecules/FormField'
export { Gated } from './molecules/Gated'
export type { GatedProps } from './molecules/Gated'
export { PageHeader } from './molecules/PageHeader'
export type { PageHeaderProps } from './molecules/PageHeader'
export { SegmentedControl } from './molecules/SegmentedControl'
export type { SegmentedControlProps, SegmentOption } from './molecules/SegmentedControl'
export { StatCard } from './molecules/StatCard'
export type { StatCardProps } from './molecules/StatCard'

// organisms — 상태 화면
export { ApiErrorState } from './organisms/states/ApiErrorState'
export type { ApiErrorStateProps } from './organisms/states/ApiErrorState'
export { EmptyState } from './organisms/states/EmptyState'
export type { EmptyStateProps } from './organisms/states/EmptyState'
export { ErrorState } from './organisms/states/ErrorState'
export type { ErrorStateProps } from './organisms/states/ErrorState'
export { ForbiddenState } from './organisms/states/ForbiddenState'
export type { ForbiddenStateProps } from './organisms/states/ForbiddenState'
export { LoadingState } from './organisms/states/LoadingState'
export type { LoadingStateProps } from './organisms/states/LoadingState'
export { NotFoundState } from './organisms/states/NotFoundState'
export type { NotFoundStateProps } from './organisms/states/NotFoundState'
export { SessionExpiredState } from './organisms/states/SessionExpiredState'
export type { SessionExpiredStateProps } from './organisms/states/SessionExpiredState'
export { StateView } from './organisms/states/StateView'
export type { StateTone, StateViewProps } from './organisms/states/StateView'

// organisms — 상단바 · 메뉴
export { MobileNav } from './organisms/MobileNav'
export type { MobileNavProps } from './organisms/MobileNav'
export { Brand } from './organisms/nav/Brand'
export type { BrandProps } from './organisms/nav/Brand'
export { findNavItem } from './organisms/nav/nav-items'
export type { NavGroup, NavHit, NavItem } from './organisms/nav/nav-items'
export { NavMenu } from './organisms/nav/NavMenu'
export type { NavMenuProps } from './organisms/nav/NavMenu'
export { SensorSummary } from './organisms/nav/SensorSummary'
export type { SensorSummaryProps } from './organisms/nav/SensorSummary'
export { LogoutForm, UserPanel } from './organisms/nav/UserPanel'
export type { LogoutFormProps, UserPanelProps } from './organisms/nav/UserPanel'
export { SideNav } from './organisms/SideNav'
export type { SideNavProps } from './organisms/SideNav'
export { TopBar } from './organisms/TopBar'
export type { TopBarProps } from './organisms/TopBar'

// templates
export { AppLayout } from './templates/AppLayout'
export type { AppLayoutProps } from './templates/AppLayout'
export { breadcrumbsFor } from './templates/breadcrumbs'
export type { CrumbMatch, RouteHandle } from './templates/breadcrumbs'
